### PR TITLE
fix: :bug: disposing before stop events has been prevented

### LINKED ISSUE #2: AnimationController.stop() called after AnimationController.dispose()
AnimationController keeps on running even after dispose called. This issue leads to crashes on sudden stop/restart related triggers on RippleAnimation. 

**Error log:** 

```dart
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 772 pos 7: '_ticker != null': AnimationController.stop() called after AnimationController.dispose()
animation_controller.dart:772
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      AnimationController.stop
animation_controller.dart:772
#3      AnimationController.repeat
animation_controller.dart:653
#4      RippleAnimationState.initState.<anonymous closure>
simple_ripple_animation.dart:61
#5      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#6      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#7      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:4<…>
```

### PR DESCRIPTION
**Pull request by furkanarslann**
Closes #2

### CODE REVIEW

**Comment by furkanarslann** [comment]
CC: @jemisgoti

**Comment by jemisgoti** [comment]
@furkanarslann Thank you for the PR

**Comment by jemisgoti** [comment]
@furkanarslann New version is launched with your fixes. Now you can use latest version. 
Ref: https://pub.dev/packages/simple_ripple_animation/versions/0.0.8

**Comment by furkanarslann** [comment]
> @furkanarslann New version is launched with your fixes. Now you can use latest version. 
> 
> Ref: https://pub.dev/packages/simple_ripple_animation/versions/0.0.8

Thank you for publishing rapidly🙌🏻

**Pull request merged**
